portal_home:
    path: /home
    controller: 'App\Controller\PortalController::index'

portal_login:
    path: /login
    controller: 'App\Controller\SecurityController::login'

portal_login_check:
    path: /login_check

portal_logout:
    path: /logout


# Clients

portal_client_new:
    path: /client/new
    controller: 'App\Controller\ClientController::new'