portal_home:
    path: /home
    controller: 'App\Controller\PortalController::index'

portal_restore:
    path: /restore/{sessionId}
    controller: 'App\Controller\PortalController::restore'

portal_login:
    path: /login
    controller: 'App\Controller\SecurityController::login'

portal_login_check:
    path: /login_check

portal_logout:
    path: /logout


# Clients

portal_clients:
    path: /clients
    controller: 'App\Controller\ClientController::list'

portal_client_new:
    path: /client/new
    controller: 'App\Controller\ClientController::new'

# Schedules

portal_schedule_new:
    path: /schedule/new
    controller: 'App\Controller\ScheduleController::new'

# Datalists

portal_backup:
    path: /backup
    controller: 'App\Controller\DatalistController::backup'

portal_backup_azure:
    path: /backup/azure/{id}
    controller: 'App\Controller\DatalistController::backupAzure'

portal_backup_local:
    path: /backup/local/{id}
    controller: 'App\Controller\DatalistController::backupLocal'