portal_home:
    path: /home
    controller: 'App\Controller\PortalController::index'

portal_login:
    path: /login
    controller: 'App\Security\Controller\SecurityController::login'

portal_login_check:
    path: /login_check

portal_logout:
    path: /logout